# Generated by Django 4.2.28 on 2026-03-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0120_issueview_archived_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="openclaw_agent_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="openclaw_notify_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
